openapi: 3.0.0
info:
  title: Bulk Load data
  version: '1.0'
  description: |-
    This api allows to bulk load observations and related metadata such as, the session of data collection, the subject of data collection, and the producer that generated the data.

    This API is protected using OAuth2 tokens. You need an OAuth2 token in order to load data through the bulk load data endpoint. To get oauth2 tokens, you need to authenticate using a client_id and a client_secret which are supplied to the Get Authorization Keys endpoint using query parameters.
servers:
  - url: 'https://api-bah.kinduct.com'
    description: Production
paths:
  /oauth/token:
    get:
      summary: API - Get Authorization Tokens
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: object
                    properties:
                      token:
                        type: string
                      expiresAt:
                        type: string
                  refreshToken:
                    type: object
                    properties:
                      token:
                        type: string
                      expiresAt:
                        type: string
              examples:
                example-token:
                  value:
                    accessToken:
                      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
                      expiresAt: '2020-02-14T17:04:35+0000'
                    refreshToken:
                      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
                      expiresAt: '2020-02-14T17:04:35+0000'
        '':
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  expires_in:
                    type: number
                  token_type:
                    type: string
                    description: ''
              examples:
                example-1:
                  value:
                    access_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlFUazBPRGhDT0RaRk1EUTROREpFTVVNNU5VVXpSRUpHUkRGRE9ERkRRakZETlRNMk1VRkdSUSJ9.eyJpc3MiOiJodHRwczovL2tpbmR1Y3QtZ2FtZXMuYXV0aDAuY29tLyIsInN1YiI6IjYxOVdRd0lZQWRnWm9kc1l0eU1LQXpvekFuTnJnR0JwQGNsaWVudHMiLCJhdWQiOiJodHRwczovL29ic2VydmF0aW9ucy5raW5kdWN0LmNvZGVzIiwiaWF0IjoxNTgzNDExMDE5LCJleHAiOjE1ODM0OTc0MTksImF6cCI6IjYxOVdRd0lZQWRnWm9kc1l0eU1LQXpvekFuTnJnR0JwIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.ZIjP9DZvVhTisDzpe7ysL0S-mZTmXA0SPVQpSvlB4RppHgCVjO7UFw6ycHyh2rOHauJyplORnHhfkR6Lx5T4uwAPEALPDiKIzoRDOWwzlGM1jAA9wPS6Db0G4mr3mzrVxHXZ8A1m20hNNIUKpCwnaW35iPmYcY0z82wgpJNpVEKb7m3e4H0g4btk2vBVL2U7f5PBC0GeLgRrrQqgMJVlV5uVk2A20EaqGuCwbBinIg3SoZEuKcoOTunwYnSRu9b2-tmqSeUTkFku5dBhAE3aNGiMHBSnxtSZ36GxpOslJXxEn_6mxQttX-if41xFyjJYLps79WfMRYx5fnKZdThPzA
                    expires_in: 86400
                    token_type: Bearer
          description: The oauth2 token used later to authorize requests to the api
      operationId: get-tokens
      description: Get JWT access and refresh tokens. This requires valid credentials specied using a supplied client_id and client_secret
      requestBody: {}
      parameters:
        - schema:
            type: string
          in: query
          name: client_id
          description: The authentication client id as per oauth2 client credentials workfloww
          required: true
        - schema:
            type: string
          in: query
          name: client_secret
          description: The authentication client secret as per oauth2 client credentials workflow
          required: true
    parameters: []
  /v1/dataSets:
    post:
      summary: API - Bulk Load Data
      operationId: post-data_sets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSet'
              examples:
                observations-without-session:
                  value:
                    observations:
                      - observedAt: '2020-02-18T00:50:00+0000'
                        identifier: finalScore
                        valueString: null
                        valueDecimal: 809
                        valueInteger: null
                    identifier: DataSet 1
                    dataProducer:
                      identifier: VR Vive
                    subject:
                      identifier: Lujan Isaac
                    sessions:
                      - endedAt: '2020-02-18T00:10:00+0000'
                        startedAt: '2020-02-18T00:00:00+0000'
                        identifier: '1'
                        observations:
                          - observedAt: '2020-02-18T00:01:00+0000'
                            identifier: ArousalAverage
                            valueString: null
                            valueDecimal: 2.07
                            valueInteger: null
                          - observedAt: '2020-02-18T00:02:00+0000'
                            identifier: AverageTimeToDecide
                            valueString: null
                            valueDecimal: 1.18
                            valueInteger: null
                          - observedAt: '2020-02-18T00:03:00+0000'
                            identifier: CorrectShots
                            valueString: null
                            valueDecimal: 2
                            valueInteger: null
                          - observedAt: '2020-02-18T00:04:00+0000'
                            identifier: HighestArousal
                            valueString: null
                            valueDecimal: 15.83
                            valueInteger: null
                          - observedAt: '2020-02-18T00:05:00+0000'
                            identifier: LargestArousalDelta
                            valueString: null
                            valueDecimal: null
                            valueInteger: 13
                          - observedAt: '2020-02-18T00:06:00+0000'
                            identifier: LowestArousal
                            valueString: null
                            valueDecimal: null
                            valueInteger: 6
                          - observedAt: '2020-02-18T00:07:00+0000'
                            identifier: WrongShots
                            valueString: null
                            valueDecimal: null
                            valueInteger: 20
                      - endedAt: '2020-02-18T00:25:00+0000'
                        startedAt: '2020-02-18T00:15:00+0000'
                        identifier: '2'
                        observations:
                          - observedAt: '2020-02-18T00:16:00+0000'
                            identifier: ArousalAverage
                            valueString: null
                            valueDecimal: 2.07
                            valueInteger: null
                          - observedAt: '2020-02-18T00:17:00+0000'
                            identifier: AverageTimeToDecide
                            valueString: null
                            valueDecimal: 1.18
                            valueInteger: null
                          - observedAt: '2020-02-18T00:18:00+0000'
                            identifier: CorrectShots
                            valueString: null
                            valueDecimal: null
                            valueInteger: 2
                          - observedAt: '2020-02-18T00:19:00+0000'
                            identifier: HighestArousal
                            valueString: null
                            valueDecimal: 15.83
                            valueInteger: null
                          - observedAt: '2020-02-18T00:20:00+0000'
                            identifier: LargestArousalDelta
                            valueString: null
                            valueDecimal: null
                            valueInteger: 13
                          - observedAt: '2020-02-18T00:21:00+0000'
                            identifier: LowestArousal
                            valueString: null
                            valueDecimal: null
                            valueInteger: 6
                          - observedAt: '2020-02-18T00:22:00+0000'
                            identifier: WrongShots
                            valueString: null
                            valueDecimal: null
                            valueInteger: 20
                      - endedAt: '2020-02-18T00:40:00+0000'
                        startedAt: '2020-02-18T00:30:00+0000'
                        identifier: '3'
                        observations:
                          - observedAt: '2020-02-18T00:31:00+0000'
                            identifier: ArousalAverage
                            valueString: null
                            valueDecimal: 2.07
                            valueInteger: null
                          - observedAt: '2020-02-18T00:32:00+0000'
                            identifier: AverageTimeToDecide
                            valueString: null
                            valueDecimal: 1.18
                            valueInteger: null
                          - observedAt: '2020-02-18T00:33:00+0000'
                            identifier: CorrectShots
                            valueString: null
                            valueDecimal: null
                            valueInteger: 2
                          - observedAt: '2020-02-18T00:34:00+0000'
                            identifier: HighestArousal
                            valueString: null
                            valueDecimal: 15.83
                            valueInteger: null
                          - observedAt: '2020-02-18T00:35:00+0000'
                            identifier: LargestArousalDelta
                            valueString: null
                            valueDecimal: null
                            valueInteger: 13
                          - observedAt: '2020-02-18T00:36:00+0000'
                            identifier: LowestArousal
                            valueString: null
                            valueDecimal: null
                            valueInteger: 6
                          - observedAt: '2020-02-18T00:37:00+0000'
                            identifier: WrongShots
                            valueString: null
                            valueDecimal: null
                            valueInteger: 20
      description: |-
        Upload a data set. A data set is a collection of information including:
        1) The producer that generated the data
        2) The session withint which data was collected. This is optional.
        3) The subject of the data collection
        4) One or more observations collected

        This is a secure api call which requires an Authorization header that includes a bearer access token. For examples of payload and response, checkout the accompanied examples.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                dataProducer:
                  type: object
                  required:
                    - identifier
                  properties:
                    identifier:
                      type: string
                subject:
                  type: object
                  required:
                    - identifier
                  properties:
                    identifier:
                      type: string
                    description:
                      type: string
                observations:
                  type: array
                  items:
                    type: object
                    properties:
                      identifier:
                        type: string
                        minLength: 1
                        maxLength: 100
                      valueDecimal:
                        type: number
                      valueInteger:
                        type: integer
                      valueString:
                        type: string
                      observedAt:
                        type: string
                        format: date-time
                    required:
                      - identifier
                identifier:
                  type: string
                  minLength: 1
                  maxLength: 100
                sessions:
                  type: array
                  items:
                    type: object
                    properties:
                      identifier:
                        type: string
                      startedAt:
                        type: string
                      endedAt:
                        type: string
                      observations:
                        type: array
                        items:
                          type: object
                          properties:
                            identifier:
                              type: string
                            observedAt:
                              type: string
                              format: date-time
                            valueInteger:
                              type: integer
                            valueDecimal:
                              type: number
                            valueString:
                              type: string
                          required:
                            - identifier
              required:
                - dataProducer
                - subject
                - observations
                - identifier
            examples:
              example-1:
                value:
                  identifier: DataSet 1
                  dataProducer:
                    identifier: VR Vive
                  subject:
                    identifier: Lujan Isaac
                  sessions:
                    - identifier: '1'
                      startedAt: '2020-02-18T00:00:00+0000'
                      endedAt: '2020-02-18T00:10:00+0000'
                      observations:
                        - identifier: ArousalAverage
                          observedAt: '2020-02-18T00:01:00+0000'
                          valueDecimal: 2.07
                        - identifier: AverageTimeToDecide
                          observedAt: '2020-02-18T00:02:00+0000'
                          valueDecimal: 1.18
                        - identifier: CorrectShots
                          observedAt: '2020-02-18T00:03:00+0000'
                          valueDecimal: 2
                        - identifier: HighestArousal
                          observedAt: '2020-02-18T00:04:00+0000'
                          valueDecimal: 15.83
                        - identifier: LargestArousalDelta
                          observedAt: '2020-02-18T00:05:00+0000'
                          valueInteger: 13
                        - identifier: LowestArousal
                          observedAt: '2020-02-18T00:06:00+0000'
                          valueInteger: 6
                        - identifier: WrongShots
                          observedAt: '2020-02-18T00:07:00+0000'
                          valueInteger: 20
                    - identifier: '2'
                      startedAt: '2020-02-18T00:15:00+0000'
                      endedAt: '2020-02-18T00:25:00+0000'
                      observations:
                        - identifier: ArousalAverage
                          observedAt: '2020-02-18T00:16:00+0000'
                          valueDecimal: 2.07
                        - identifier: AverageTimeToDecide
                          observedAt: '2020-02-18T00:17:00+0000'
                          valueDecimal: 1.18
                        - identifier: CorrectShots
                          observedAt: '2020-02-18T00:18:00+0000'
                          valueInteger: 2
                        - identifier: HighestArousal
                          observedAt: '2020-02-18T00:19:00+0000'
                          valueDecimal: 15.83
                        - identifier: LargestArousalDelta
                          observedAt: '2020-02-18T00:20:00+0000'
                          valueInteger: 13
                        - identifier: LowestArousal
                          observedAt: '2020-02-18T00:21:00+0000'
                          valueInteger: 6
                        - identifier: WrongShots
                          observedAt: '2020-02-18T00:22:00+0000'
                          valueInteger: 20
                    - identifier: '3'
                      startedAt: '2020-02-18T00:30:00+0000'
                      endedAt: '2020-02-18T00:40:00+0000'
                      observations:
                        - identifier: ArousalAverage
                          observedAt: '2020-02-18T00:31:00+0000'
                          valueDecimal: 2.07
                        - identifier: AverageTimeToDecide
                          observedAt: '2020-02-18T00:32:00+0000'
                          valueDecimal: 1.18
                        - identifier: CorrectShots
                          observedAt: '2020-02-18T00:33:00+0000'
                          valueInteger: 2
                        - identifier: HighestArousal
                          observedAt: '2020-02-18T00:34:00+0000'
                          valueDecimal: 15.83
                        - identifier: LargestArousalDelta
                          observedAt: '2020-02-18T00:35:00+0000'
                          valueInteger: 13
                        - identifier: LowestArousal
                          observedAt: '2020-02-18T00:36:00+0000'
                          valueInteger: 6
                        - identifier: WrongShots
                          observedAt: '2020-02-18T00:37:00+0000'
                          valueInteger: 20
                  observations:
                    - identifier: finalScore
                      observedAt: '2020-02-18T00:50:00+0000'
                      valueDecimal: 809
              example-2:
                value:
                  identifier: DataSet 2
                  dataProducer:
                    identifier: VR Vive
                  subject:
                    identifier: Hatch Kyle
                  sessions:
                    - identifier: '1'
                      startedAt: '2020-02-18T00:00:00+0000'
                      endedAt: '2020-02-18T00:10:00+0000'
                      observations:
                        - identifier: ArousalAverage
                          observedAt: '2020-02-18T00:01:00+0000'
                          valueDecimal: 2.47
                        - identifier: AverageTimeToDecide
                          observedAt: '2020-02-18T00:02:00+0000'
                          valueDecimal: 1.7
                        - identifier: CorrectShots
                          observedAt: '2020-02-18T00:03:00+0000'
                          valueDecimal: 4
                        - identifier: HighestArousal
                          observedAt: '2020-02-18T00:04:00+0000'
                          valueDecimal: 10.17
                        - identifier: LargestArousalDelta
                          observedAt: '2020-02-18T00:05:00+0000'
                          valueDecimal: 20.25
                        - identifier: LowestArousal
                          observedAt: '2020-02-18T00:06:00+0000'
                          valueDecimal: 9.33
                        - identifier: WrongShots
                          observedAt: '2020-02-18T00:07:00+0000'
                          valueDecimal: 14
                    - identifier: '2'
                      startedAt: '2020-02-18T00:00:00+0000'
                      endedAt: '2020-02-18T00:10:00+0000'
                      observations:
                        - identifier: ArousalAverage
                          observedAt: '2020-02-18T00:01:00+0000'
                          valueDecimal: 2.47
                        - identifier: AverageTimeToDecide
                          observedAt: '2020-02-18T00:02:00+0000'
                          valueDecimal: 1.7
                        - identifier: CorrectShots
                          observedAt: '2020-02-18T00:03:00+0000'
                          valueDecimal: 4
                        - identifier: HighestArousal
                          observedAt: '2020-02-18T00:04:00+0000'
                          valueDecimal: 10.17
                        - identifier: LargestArousalDelta
                          observedAt: '2020-02-18T00:05:00+0000'
                          valueDecimal: 20.25
                        - identifier: LowestArousal
                          observedAt: '2020-02-18T00:06:00+0000'
                          valueDecimal: 9.33
                        - identifier: WrongShots
                          observedAt: '2020-02-18T00:07:00+0000'
                          valueDecimal: 14
                    - identifier: '3'
                      startedAt: '2020-02-18T00:00:00+0000'
                      endedAt: '2020-02-18T00:10:00+0000'
                      observations:
                        - identifier: ArousalAverage
                          observedAt: '2020-02-18T00:01:00+0000'
                          valueDecimal: 2.47
                        - identifier: AverageTimeToDecide
                          observedAt: '2020-02-18T00:02:00+0000'
                          valueDecimal: 1.7
                        - identifier: CorrectShots
                          observedAt: '2020-02-18T00:03:00+0000'
                          valueDecimal: 4
                        - identifier: HighestArousal
                          observedAt: '2020-02-18T00:04:00+0000'
                          valueDecimal: 10.17
                        - identifier: LargestArousalDelta
                          observedAt: '2020-02-18T00:05:00+0000'
                          valueDecimal: 20.25
                        - identifier: LowestArousal
                          observedAt: '2020-02-18T00:06:00+0000'
                          valueDecimal: 9.33
                        - identifier: WrongShots
                          observedAt: '2020-02-18T00:07:00+0000'
                          valueDecimal: 14
                  observations:
                    - identifier: finalScore
                      observedAt: '2020-02-18T00:50:00+0000'
                      valueDecimal: 864
        description: Bulk load data
      security:
        - Access TokensBasic Authentication: []
    parameters: []
  /v1/stats:
    get:
      summary: API - Get Statistics
      tags: []
      responses: {}
      operationId: get-stats
      description: Retrieve counts for data stored in the api
      security:
        - Access TokensBasic Authentication: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                observationsCount:
                  type: number
                sessionsCount:
                  type: number
                subjectsCount:
                  type: number
                dataSetsCounts:
                  type: number
            examples:
              example-1:
                value:
                  sessionsCount: 10
                  dataSetsCount: 4
                  observationsCount: 62
                  subjectsCount: 3
        description: ''
    parameters: []
components:
  schemas:
    DataSet:
      title: DataSet
      type: object
      description: A collection of observations for a given subject that was observed during a session.
      x-examples:
        example-one:
          observations:
            - observedAt: '2020-02-18T00:50:00+0000'
              identifier: finalScore
              valueString: null
              valueDecimal: 809
              valueInteger: null
          identifier: DataSet 1
          dataProducer:
            identifier: VR Vive
          subject:
            identifier: Lujan Isaac
          sessions:
            - endedAt: '2020-02-18T00:10:00+0000'
              startedAt: '2020-02-18T00:00:00+0000'
              identifier: '1'
              observations:
                - observedAt: '2020-02-18T00:01:00+0000'
                  identifier: ArousalAverage
                  valueString: null
                  valueDecimal: 2.07
                  valueInteger: null
                - observedAt: '2020-02-18T00:02:00+0000'
                  identifier: AverageTimeToDecide
                  valueString: null
                  valueDecimal: 1.18
                  valueInteger: null
                - observedAt: '2020-02-18T00:03:00+0000'
                  identifier: CorrectShots
                  valueString: null
                  valueDecimal: 2
                  valueInteger: null
                - observedAt: '2020-02-18T00:04:00+0000'
                  identifier: HighestArousal
                  valueString: null
                  valueDecimal: 15.83
                  valueInteger: null
                - observedAt: '2020-02-18T00:05:00+0000'
                  identifier: LargestArousalDelta
                  valueString: null
                  valueDecimal: null
                  valueInteger: 13
                - observedAt: '2020-02-18T00:06:00+0000'
                  identifier: LowestArousal
                  valueString: null
                  valueDecimal: null
                  valueInteger: 6
                - observedAt: '2020-02-18T00:07:00+0000'
                  identifier: WrongShots
                  valueString: null
                  valueDecimal: null
                  valueInteger: 20
            - endedAt: '2020-02-18T00:25:00+0000'
              startedAt: '2020-02-18T00:15:00+0000'
              identifier: '2'
              observations:
                - observedAt: '2020-02-18T00:16:00+0000'
                  identifier: ArousalAverage
                  valueString: null
                  valueDecimal: 2.07
                  valueInteger: null
                - observedAt: '2020-02-18T00:17:00+0000'
                  identifier: AverageTimeToDecide
                  valueString: null
                  valueDecimal: 1.18
                  valueInteger: null
                - observedAt: '2020-02-18T00:18:00+0000'
                  identifier: CorrectShots
                  valueString: null
                  valueDecimal: null
                  valueInteger: 2
                - observedAt: '2020-02-18T00:19:00+0000'
                  identifier: HighestArousal
                  valueString: null
                  valueDecimal: 15.83
                  valueInteger: null
                - observedAt: '2020-02-18T00:20:00+0000'
                  identifier: LargestArousalDelta
                  valueString: null
                  valueDecimal: null
                  valueInteger: 13
                - observedAt: '2020-02-18T00:21:00+0000'
                  identifier: LowestArousal
                  valueString: null
                  valueDecimal: null
                  valueInteger: 6
                - observedAt: '2020-02-18T00:22:00+0000'
                  identifier: WrongShots
                  valueString: null
                  valueDecimal: null
                  valueInteger: 20
            - endedAt: '2020-02-18T00:40:00+0000'
              startedAt: '2020-02-18T00:30:00+0000'
              identifier: '3'
              observations:
                - observedAt: '2020-02-18T00:31:00+0000'
                  identifier: ArousalAverage
                  valueString: null
                  valueDecimal: 2.07
                  valueInteger: null
                - observedAt: '2020-02-18T00:32:00+0000'
                  identifier: AverageTimeToDecide
                  valueString: null
                  valueDecimal: 1.18
                  valueInteger: null
                - observedAt: '2020-02-18T00:33:00+0000'
                  identifier: CorrectShots
                  valueString: null
                  valueDecimal: null
                  valueInteger: 2
                - observedAt: '2020-02-18T00:34:00+0000'
                  identifier: HighestArousal
                  valueString: null
                  valueDecimal: 15.83
                  valueInteger: null
                - observedAt: '2020-02-18T00:35:00+0000'
                  identifier: LargestArousalDelta
                  valueString: null
                  valueDecimal: null
                  valueInteger: 13
                - observedAt: '2020-02-18T00:36:00+0000'
                  identifier: LowestArousal
                  valueString: null
                  valueDecimal: null
                  valueInteger: 6
                - observedAt: '2020-02-18T00:37:00+0000'
                  identifier: WrongShots
                  valueString: null
                  valueDecimal: null
                  valueInteger: 20
      properties:
        identifier:
          type: string
          minLength: 1
          maxLength: 100
        dataProducer:
          type: object
          required:
            - identifier
          properties:
            identifier:
              type: string
              minLength: 1
              maxLength: 100
        subject:
          $ref: '#/components/schemas/Subject'
        observations:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
        sessions:
          type: array
          items:
            $ref: '#/components/schemas/Session'
      required:
        - identifier
        - dataProducer
        - subject
        - observations
    Subject:
      title: Subject
      type: object
      description: The subject of data collection
      x-examples:
        subject-johndoe:
          identifier: eagle
      properties:
        identifier:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
      required:
        - identifier
    Observation:
      title: Observation
      type: object
      x-examples:
        example-1:
          observedAt: '2020-02-18T00:18:00+0000'
          identifier: CorrectShots
          valueString: null
          valueDecimal: null
          valueInteger: 2
        example-2:
          observedAt: '2020-02-18T00:17:00+0000'
          identifier: AverageTimeToDecide
          valueString: null
          valueDecimal: 1.18
          valueInteger: null
      description: The actual data observed or derived from data observed. Exactly one of the valueX fields is required. Check examples for more information.
      properties:
        identifier:
          type: string
          minLength: 1
          maxLength: 100
        valueInteger:
          type: integer
        valueDecimal:
          type: number
        valueString:
          type: string
        observedAt:
          type: string
          format: date-time
      required:
        - identifier
    Session:
      title: Session
      type: object
      x-examples:
        example-trial-one:
          identifier: '1'
          startedAt: '2020-02-18T00:00:00+0000'
          endedAt: '2020-02-18T00:10:00+0000'
          observations:
            - identifier: ArousalAverage
              observedAt: '2020-02-18T00:01:00+0000'
              valueDecimal: 2.47
            - identifier: AverageTimeToDecide
              observedAt: '2020-02-18T00:02:00+0000'
              valueDecimal: 1.7
            - identifier: CorrectShots
              observedAt: '2020-02-18T00:03:00+0000'
              valueDecimal: 4
            - identifier: HighestArousal
              observedAt: '2020-02-18T00:04:00+0000'
              valueDecimal: 10.17
            - identifier: LargestArousalDelta
              observedAt: '2020-02-18T00:05:00+0000'
              valueDecimal: 20.25
            - identifier: LowestArousal
              observedAt: '2020-02-18T00:06:00+0000'
              valueDecimal: 9.33
            - identifier: WrongShots
              observedAt: '2020-02-18T00:07:00+0000'
              valueDecimal: 14
        example-trial-two:
          endedAt: '2020-02-18T00:25:00+0000'
          startedAt: '2020-02-18T00:15:00+0000'
          identifier: '2'
          observations:
            - observedAt: '2020-02-18T00:16:00+0000'
              identifier: ArousalAverage
              valueString: null
              valueDecimal: 2.07
              valueInteger: null
            - observedAt: '2020-02-18T00:17:00+0000'
              identifier: AverageTimeToDecide
              valueString: null
              valueDecimal: 1.18
              valueInteger: null
            - observedAt: '2020-02-18T00:18:00+0000'
              identifier: CorrectShots
              valueString: null
              valueDecimal: null
              valueInteger: 2
            - observedAt: '2020-02-18T00:19:00+0000'
              identifier: HighestArousal
              valueString: null
              valueDecimal: 15.83
              valueInteger: null
            - observedAt: '2020-02-18T00:20:00+0000'
              identifier: LargestArousalDelta
              valueString: null
              valueDecimal: null
              valueInteger: 13
            - observedAt: '2020-02-18T00:21:00+0000'
              identifier: LowestArousal
              valueString: null
              valueDecimal: null
              valueInteger: 6
            - observedAt: '2020-02-18T00:22:00+0000'
              identifier: WrongShots
              valueString: null
              valueDecimal: null
              valueInteger: 20
      description: The session within which data was collected.
      properties:
        identifier:
          type: string
          minLength: 1
          maxLength: 100
        startedAt:
          type: string
          format: date-time
        endedAt:
          type: string
          format: date-time
        observations:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
      required:
        - identifier
        - startedAt
        - endedAt
  securitySchemes:
    Access TokensBasic Authentication:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
